#Comments by Cristian D.

#Variables needed for the job format: VARIABLE: "value"
variables:

#Stages needed in your pipeline
stages:
    - build
    - deploy_dev
    - deploy_prod       


build: 
    stage: build
    image: node:16.17-alpine
    before_script:
        - cd ./FrontEnd/proyecto-integrador
    script:
        # Set PATH
        - export PATH=$PATH:/usr/bin/npm
        # Install Dependencies
        - npm install
        # Build App
        - CI=false npm run build
    artifacts:
       paths:
          #Build folder
          - ./FrontEnd/proyecto-integrador/build
       expire_in: 1 hour

deploy_dev:
    stage: deploy_dev
    image: python:latest
    only:
      refs:
        - Develop
    script:
        - pip3 install awscli
        - aws s3 sync ./FrontEnd/proyecto-integrador/build s3://easyridesdevelopment

deploy_prod:
    stage: deploy_dev
    image: python:latest
    only:
      refs:
        - main
    script:
        - pip3 install awscli
        - aws s3 sync ./FrontEnd/proyecto-integrador/build s3://easyridesproduction
    
            


    
